import type { InferInsertModel } from "drizzle-orm";
import type { exercises } from "../schema";

type ExerciseInsert = InferInsertModel<typeof exercises>;

export const exerciseSeedData: Omit<ExerciseInsert, "id" | "createdAt">[] = [
  // ─── CHEST (11) ────────────────────────────────────────────────────────────
  {
    slug: "barbell-bench-press",
    nameEn: "Barbell Bench Press",
    nameTh: "เบนช์เพรสบาร์เบล",
    category: "chest",
    muscleGroups: ["chest", "triceps", "shoulders"],
    equipment: "barbell",
    isBodyweight: false,
    difficulty: "intermediate",
    beginnerCueEn: "Plant feet flat, retract scapula, lower bar to mid-chest, press up in a slight arc.",
    beginnerCueTh: "วางเท้าราบ ดึงสะบักเข้า ลดบาร์ลงกลางอก แล้วดันขึ้นเป็นส่วนโค้งเล็กน้อย",
    commonMistakeEn: "Bouncing the bar off the chest or flaring elbows too wide.",
    commonMistakeTh: "กระดอนบาร์บนอก หรือกางข้อศอกออกมากเกินไป",
  },
  {
    slug: "incline-bench-press",
    nameEn: "Incline Bench Press",
    nameTh: "เบนช์เพรสเอียงขึ้น",
    category: "chest",
    muscleGroups: ["upper chest", "triceps", "shoulders"],
    equipment: "barbell",
    isBodyweight: false,
    difficulty: "intermediate",
    beginnerCueEn: "Set bench to 30–45°, press bar to upper chest, keep wrists stacked.",
    beginnerCueTh: "ปรับม้านั่งที่ 30–45° กดบาร์ไปที่อกบน รักษาข้อมือให้ตรง",
    commonMistakeEn: "Setting the incline too steep, turning it into a shoulder press.",
    commonMistakeTh: "ตั้งมุมชันเกินไปจนกลายเป็นการกดไหล่แทน",
  },
  {
    slug: "decline-bench-press",
    nameEn: "Decline Bench Press",
    nameTh: "เบนช์เพรสเอียงลง",
    category: "chest",
    muscleGroups: ["lower chest", "triceps"],
    equipment: "barbell",
    isBodyweight: false,
    difficulty: "intermediate",
    beginnerCueEn: "Secure feet, lower bar to lower chest, press in a slight arc.",
    beginnerCueTh: "ยึดเท้า ลดบาร์ไปที่อกล่าง กดขึ้นเป็นส่วนโค้งเล็กน้อย",
    commonMistakeEn: "Letting hips rise off the bench during the press.",
    commonMistakeTh: "ปล่อยให้สะโพกยกขึ้นจากม้านั่งระหว่างกด",
  },
  {
    slug: "dumbbell-fly",
    nameEn: "Dumbbell Fly",
    nameTh: "ดัมเบลฟลาย",
    category: "chest",
    muscleGroups: ["chest"],
    equipment: "dumbbell",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Keep a slight bend in elbows, lower dumbbells in a wide arc until you feel a stretch, squeeze chest to return.",
    beginnerCueTh: "งอข้อศอกเล็กน้อย ลดดัมเบลเป็นส่วนโค้งกว้างจนรู้สึกยืด แล้วบีบอกเพื่อยกกลับ",
    commonMistakeEn: "Straightening arms completely, stressing the elbow joint.",
    commonMistakeTh: "เหยียดแขนตรงทั้งหมด ทำให้ข้อศอกรับแรงเกินไป",
  },
  {
    slug: "cable-fly",
    nameEn: "Cable Fly",
    nameTh: "เคเบิลฟลาย",
    category: "chest",
    muscleGroups: ["chest"],
    equipment: "cable",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Set cables at chest height, step forward, bring handles together in a hugging motion.",
    beginnerCueTh: "ตั้งสายเคเบิลระดับอก ก้าวไปข้างหน้า ดึงแฮนเดิลเข้าหากันเหมือนกอดรัด",
    commonMistakeEn: "Using momentum and swinging the torso instead of squeezing the chest.",
    commonMistakeTh: "ใช้แรงเหวี่ยงและแกว่งลำตัวแทนที่จะบีบอก",
  },
  {
    slug: "push-up",
    nameEn: "Push-Up",
    nameTh: "วิดพื้น",
    category: "chest",
    muscleGroups: ["chest", "triceps", "shoulders", "core"],
    equipment: "bodyweight",
    isBodyweight: true,
    difficulty: "beginner",
    beginnerCueEn: "Keep body in a straight line, lower chest to floor, push back up keeping core tight.",
    beginnerCueTh: "รักษาลำตัวให้เป็นเส้นตรง ลดอกลงพื้น กดขึ้นพร้อมรักษาแกนกลางให้แน่น",
    commonMistakeEn: "Sagging hips or piking them up, breaking the straight-line position.",
    commonMistakeTh: "ปล่อยสะโพกห้อยหรือยกขึ้นสูง ทำให้ท่าไม่เป็นเส้นตรง",
  },
  {
    slug: "chest-dips",
    nameEn: "Chest Dips",
    nameTh: "ดิปส์อก",
    category: "chest",
    muscleGroups: ["chest", "triceps", "shoulders"],
    equipment: "bodyweight",
    isBodyweight: true,
    difficulty: "intermediate",
    beginnerCueEn: "Lean forward slightly, elbows slightly flared, lower until stretch in chest, press up.",
    beginnerCueTh: "เอนตัวไปข้างหน้าเล็กน้อย ข้อศอกแยกออกเล็กน้อย ลดลงจนรู้สึกยืดที่อก แล้วกดขึ้น",
    commonMistakeEn: "Keeping torso too upright, shifting stress to triceps only.",
    commonMistakeTh: "ตั้งลำตัวตรงเกินไปทำให้เน้นแค่ไตรเซ็บส์",
  },
  {
    slug: "chest-press-machine",
    nameEn: "Chest Press Machine",
    nameTh: "เครื่องกดอก",
    category: "chest",
    muscleGroups: ["chest", "triceps", "shoulders"],
    equipment: "machine",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Adjust seat so handles align with mid-chest, press forward and fully extend without locking elbows.",
    beginnerCueTh: "ปรับเบาะให้แฮนเดิลอยู่ระดับกลางอก กดไปข้างหน้าเหยียดแขนโดยไม่ล็อคข้อศอก",
    commonMistakeEn: "Arching the lower back and letting shoulders shrug up.",
    commonMistakeTh: "โก่งหลังส่วนล่างและยักไหล่ขึ้นระหว่างกด",
  },
  {
    slug: "pec-deck",
    nameEn: "Pec Deck",
    nameTh: "เพคเด็ค",
    category: "chest",
    muscleGroups: ["chest"],
    equipment: "machine",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Set elbows at shoulder height, bring pads together squeezing chest, control the return.",
    beginnerCueTh: "ตั้งข้อศอกระดับไหล่ นำแผ่นรองเข้าหากันพร้อมบีบอก ควบคุมการคืนตำแหน่ง",
    commonMistakeEn: "Allowing the weight to pull arms too far back, overstretching the shoulder joint.",
    commonMistakeTh: "ปล่อยให้น้ำหนักดึงแขนไปข้างหลังมากเกินไป ทำให้ข้อไหล่ยืดเกิน",
  },
  {
    slug: "landmine-press",
    nameEn: "Landmine Press",
    nameTh: "แลนด์ไมน์เพรส",
    category: "chest",
    muscleGroups: ["upper chest", "shoulders", "triceps"],
    equipment: "barbell",
    isBodyweight: false,
    difficulty: "intermediate",
    beginnerCueEn: "Hold end of barbell at shoulder height, press upward and forward in a slight arc.",
    beginnerCueTh: "จับปลายบาร์เบลที่ระดับไหล่ กดขึ้นและไปข้างหน้าเป็นส่วนโค้งเล็กน้อย",
    commonMistakeEn: "Using too much leg drive or rotating the torso during the press.",
    commonMistakeTh: "ใช้แรงขาหรือหมุนลำตัวมากเกินไประหว่างกด",
  },
  {
    slug: "svend-press",
    nameEn: "Svend Press",
    nameTh: "สเวนด์เพรส",
    category: "chest",
    muscleGroups: ["chest", "shoulders"],
    equipment: "other",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Squeeze two plates together, press forward and retract, maintain constant inward pressure.",
    beginnerCueTh: "บีบแผ่นน้ำหนักสองแผ่นเข้าหากัน กดออกไปข้างหน้าแล้วดึงกลับ รักษาแรงกดเข้าตลอด",
    commonMistakeEn: "Releasing pressure on the plates during the movement.",
    commonMistakeTh: "คลายแรงกดระหว่างการเคลื่อนไหว",
  },

  // ─── BACK (11) ─────────────────────────────────────────────────────────────
  {
    slug: "deadlift",
    nameEn: "Deadlift",
    nameTh: "เดดลิฟต์",
    category: "back",
    muscleGroups: ["back", "glutes", "hamstrings", "traps"],
    equipment: "barbell",
    isBodyweight: false,
    difficulty: "intermediate",
    beginnerCueEn: "Hip-hinge back, bar over mid-foot, drive floor away, lock hips at top.",
    beginnerCueTh: "พับสะโพกไปข้างหลัง บาร์อยู่เหนือกลางเท้า ดันพื้นออก ล็อคสะโพกด้านบน",
    commonMistakeEn: "Rounding the lower back or jerking the bar off the floor.",
    commonMistakeTh: "โค้งหลังส่วนล่างหรือกระชากบาร์ขึ้นจากพื้น",
  },
  {
    slug: "barbell-row",
    nameEn: "Barbell Row",
    nameTh: "บาร์เบลโรว์",
    category: "back",
    muscleGroups: ["back", "biceps", "rear delts"],
    equipment: "barbell",
    isBodyweight: false,
    difficulty: "intermediate",
    beginnerCueEn: "Hinge to ~45°, pull bar to lower chest, lead with elbows.",
    beginnerCueTh: "พับตัวประมาณ 45° ดึงบาร์ขึ้นไปยังอกล่าง นำด้วยข้อศอก",
    commonMistakeEn: "Using too much hip swing to jerk the weight up.",
    commonMistakeTh: "ใช้การแกว่งสะโพกมากเกินไปเพื่อกระชากน้ำหนักขึ้น",
  },
  {
    slug: "pull-up",
    nameEn: "Pull-Up",
    nameTh: "พูลอัพ",
    category: "back",
    muscleGroups: ["back", "biceps", "rear delts"],
    equipment: "bodyweight",
    isBodyweight: true,
    difficulty: "intermediate",
    beginnerCueEn: "Hang with overhand grip, depress scapula, pull chest to bar.",
    beginnerCueTh: "แขวนด้วยมือคว่ำ กดสะบักลง ดึงอกขึ้นไปหาบาร์",
    commonMistakeEn: "Kipping or using momentum instead of strict pulling strength.",
    commonMistakeTh: "โยกตัวหรือใช้แรงเหวี่ยงแทนความแข็งแรงของการดึงแบบเคร่งครัด",
  },
  {
    slug: "lat-pulldown",
    nameEn: "Lat Pulldown",
    nameTh: "แลทพูลดาวน์",
    category: "back",
    muscleGroups: ["lats", "biceps"],
    equipment: "cable",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Lean back slightly, pull bar to upper chest, squeeze lats at bottom.",
    beginnerCueTh: "เอนไปข้างหลังเล็กน้อย ดึงบาร์ลงมาที่อกบน บีบแลทด้านล่าง",
    commonMistakeEn: "Pulling behind the neck, which strains the cervical spine.",
    commonMistakeTh: "ดึงลงไปด้านหลังคอ ซึ่งทำให้กระดูกสันหลังส่วนคอรับแรงเกิน",
  },
  {
    slug: "seated-cable-row",
    nameEn: "Seated Cable Row",
    nameTh: "นั่งดึงเคเบิล",
    category: "back",
    muscleGroups: ["back", "biceps", "rear delts"],
    equipment: "cable",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Sit tall, pull handle to navel, squeeze shoulder blades together.",
    beginnerCueTh: "นั่งตัวตรง ดึงแฮนเดิลมาที่สะดือ บีบสะบักเข้าหากัน",
    commonMistakeEn: "Rocking back and forth, using lower back instead of pulling muscles.",
    commonMistakeTh: "โยกตัวไปมา ใช้หลังส่วนล่างแทนกล้ามเนื้อดึง",
  },
  {
    slug: "dumbbell-row",
    nameEn: "Dumbbell Row",
    nameTh: "ดัมเบลโรว์",
    category: "back",
    muscleGroups: ["back", "biceps"],
    equipment: "dumbbell",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Support on bench, pull dumbbell to hip, keep elbow close to body.",
    beginnerCueTh: "ค้ำที่ม้านั่ง ดึงดัมเบลขึ้นไปยังสะโพก รักษาข้อศอกให้ชิดลำตัว",
    commonMistakeEn: "Rotating the shoulder instead of driving the elbow up.",
    commonMistakeTh: "หมุนไหล่แทนที่จะดึงข้อศอกขึ้น",
  },
  {
    slug: "t-bar-row",
    nameEn: "T-Bar Row",
    nameTh: "ที-บาร์โรว์",
    category: "back",
    muscleGroups: ["back", "biceps", "rear delts"],
    equipment: "barbell",
    isBodyweight: false,
    difficulty: "intermediate",
    beginnerCueEn: "Straddle bar, hinge forward, pull to lower chest, keep back flat.",
    beginnerCueTh: "คร่อมบาร์ พับตัวไปข้างหน้า ดึงขึ้นไปยังอกล่าง รักษาหลังให้แบน",
    commonMistakeEn: "Rounding the spine under heavy load.",
    commonMistakeTh: "โค้งกระดูกสันหลังเมื่อน้ำหนักหนัก",
  },
  {
    slug: "face-pull",
    nameEn: "Face Pull",
    nameTh: "เฟซพูล",
    category: "back",
    muscleGroups: ["rear delts", "traps", "external rotators"],
    equipment: "cable",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Set cable at upper chest height, pull rope to face, elbows flared, externally rotate at end.",
    beginnerCueTh: "ตั้งเคเบิลระดับอกบน ดึงเชือกมาที่ใบหน้า ข้อศอกกาง หมุนออกที่จุดสุดท้าย",
    commonMistakeEn: "Using too much weight and losing the external rotation at the end.",
    commonMistakeTh: "ใช้น้ำหนักมากเกินไปและเสียการหมุนออกตอนท้าย",
  },
  {
    slug: "shrug",
    nameEn: "Barbell Shrug",
    nameTh: "บาร์เบลชรัก",
    category: "back",
    muscleGroups: ["traps"],
    equipment: "barbell",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Hold barbell at hips, shrug shoulders straight up, hold briefly, lower slowly.",
    beginnerCueTh: "ถือบาร์เบลที่สะโพก ยักไหล่ขึ้นตรงๆ ค้างสักครู่ แล้วลดลงช้าๆ",
    commonMistakeEn: "Rolling shoulders in a circle, which doesn't add benefit and risks injury.",
    commonMistakeTh: "หมุนไหล่เป็นวงกลม ซึ่งไม่เพิ่มประสิทธิภาพและเสี่ยงบาดเจ็บ",
  },
  {
    slug: "rack-pull",
    nameEn: "Rack Pull",
    nameTh: "แรคพูล",
    category: "back",
    muscleGroups: ["back", "traps", "glutes"],
    equipment: "barbell",
    isBodyweight: false,
    difficulty: "intermediate",
    beginnerCueEn: "Set safety bars at knee height, deadlift from that height, focus on lockout.",
    beginnerCueTh: "ตั้งแท่งนิรภัยที่ระดับเข่า ทำเดดลิฟต์จากความสูงนั้น เน้นการล็อคที่ด้านบน",
    commonMistakeEn: "Setting pins too high and only training a tiny range of motion.",
    commonMistakeTh: "ตั้งพินสูงเกินไปและฝึกแค่ช่วงการเคลื่อนไหวเล็กน้อย",
  },
  {
    slug: "good-morning",
    nameEn: "Good Morning",
    nameTh: "กู๊ดมอร์นิ่ง",
    category: "back",
    muscleGroups: ["hamstrings", "lower back", "glutes"],
    equipment: "barbell",
    isBodyweight: false,
    difficulty: "intermediate",
    beginnerCueEn: "Bar on upper back, hip hinge with soft knee bend, lower until back is near parallel to floor.",
    beginnerCueTh: "บาร์บนหลังส่วนบน พับสะโพกพร้อมงอเข่าเล็กน้อย ลดจนหลังเกือบขนานพื้น",
    commonMistakeEn: "Bending the knees too much, turning it into a squat.",
    commonMistakeTh: "งอเข่ามากเกินไปจนกลายเป็นสควอต",
  },

  // ─── LEGS (15) ─────────────────────────────────────────────────────────────
  {
    slug: "squat",
    nameEn: "Barbell Back Squat",
    nameTh: "สควอตบาร์เบล",
    category: "legs",
    muscleGroups: ["quads", "glutes", "hamstrings", "core"],
    equipment: "barbell",
    isBodyweight: false,
    difficulty: "intermediate",
    beginnerCueEn: "Bar on upper traps, hip-width stance, squat to parallel, knees track over toes.",
    beginnerCueTh: "วางบาร์บนแทรพส์ส่วนบน ยืนกว้างระดับสะโพก สควอตถึงแนวขนาน เข่าชี้ตามแนวนิ้วเท้า",
    commonMistakeEn: "Caving knees inward (valgus) under load.",
    commonMistakeTh: "เข่าพับเข้าด้านใน (วัลกัส) เมื่อน้ำหนักหนัก",
  },
  {
    slug: "front-squat",
    nameEn: "Front Squat",
    nameTh: "ฟรอนต์สควอต",
    category: "legs",
    muscleGroups: ["quads", "core", "glutes"],
    equipment: "barbell",
    isBodyweight: false,
    difficulty: "advanced",
    beginnerCueEn: "Rest bar on front delts, elbows high, stay upright throughout the squat.",
    beginnerCueTh: "วางบาร์บนสะโพกหน้า ยกข้อศอกสูง รักษาตัวตรงตลอดการสควอต",
    commonMistakeEn: "Dropping elbows and losing the bar position, causing forward lean.",
    commonMistakeTh: "ปล่อยข้อศอกตกและเสียตำแหน่งบาร์ทำให้เอนไปข้างหน้า",
  },
  {
    slug: "leg-press",
    nameEn: "Leg Press",
    nameTh: "เลกเพรส",
    category: "legs",
    muscleGroups: ["quads", "glutes", "hamstrings"],
    equipment: "machine",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Feet shoulder-width on platform, press until legs nearly straight, lower under control.",
    beginnerCueTh: "วางเท้ากว้างระดับไหล่บนแท่น กดจนขาเกือบเหยียดตรง ลดลงอย่างควบคุม",
    commonMistakeEn: "Allowing knees to cave in or lifting the lower back off the pad.",
    commonMistakeTh: "ปล่อยให้เข่าพับเข้าหรือยกหลังส่วนล่างออกจากพนัก",
  },
  {
    slug: "romanian-deadlift",
    nameEn: "Romanian Deadlift",
    nameTh: "โรมาเนียนเดดลิฟต์",
    category: "legs",
    muscleGroups: ["hamstrings", "glutes", "lower back"],
    equipment: "barbell",
    isBodyweight: false,
    difficulty: "intermediate",
    beginnerCueEn: "Hold bar at hips, push hips back, lower bar along thighs until hamstrings fully stretched.",
    beginnerCueTh: "ถือบาร์ที่สะโพก ดันสะโพกไปข้างหลัง ลดบาร์ตามต้นขาจนรู้สึกยืดแฮมสตริงเต็มที่",
    commonMistakeEn: "Bending the knees too much, turning it into a standard deadlift.",
    commonMistakeTh: "งอเข่ามากเกินไปจนกลายเป็นเดดลิฟต์ปกติ",
  },
  {
    slug: "leg-curl",
    nameEn: "Leg Curl",
    nameTh: "เลกเคิร์ล",
    category: "legs",
    muscleGroups: ["hamstrings"],
    equipment: "machine",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Lying face down, curl heels toward glutes, squeeze hamstrings, lower slowly.",
    beginnerCueTh: "นอนคว่ำ ดึงส้นเท้าขึ้นมายังก้น บีบแฮมสตริง ลดลงช้าๆ",
    commonMistakeEn: "Lifting hips off the pad to help curl heavier weight.",
    commonMistakeTh: "ยกสะโพกออกจากพนักเพื่อช่วยดึงน้ำหนักหนักขึ้น",
  },
  {
    slug: "leg-extension",
    nameEn: "Leg Extension",
    nameTh: "เลกเอ็กซ์เทนชั่น",
    category: "legs",
    muscleGroups: ["quads"],
    equipment: "machine",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Sit upright, extend legs to full extension, squeeze quads at top, lower slowly.",
    beginnerCueTh: "นั่งตรง เหยียดขาจนสุด บีบควอดส์ที่ด้านบน ลดลงช้าๆ",
    commonMistakeEn: "Swinging or jerking the weight up instead of controlled extension.",
    commonMistakeTh: "แกว่งหรือกระชากน้ำหนักขึ้นแทนการเหยียดอย่างควบคุม",
  },
  {
    slug: "calf-raise",
    nameEn: "Standing Calf Raise",
    nameTh: "เลี้ยวน่อง",
    category: "legs",
    muscleGroups: ["calves"],
    equipment: "machine",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Stand on edge of platform, raise heels as high as possible, lower until calf is stretched.",
    beginnerCueTh: "ยืนที่ขอบแท่น ยกส้นเท้าขึ้นสูงสุด ลดลงจนรู้สึกยืดน่อง",
    commonMistakeEn: "Bouncing at the bottom instead of getting a full stretch.",
    commonMistakeTh: "กระดอนที่ด้านล่างแทนที่จะยืดเต็มที่",
  },
  {
    slug: "hack-squat",
    nameEn: "Hack Squat",
    nameTh: "แฮคสควอต",
    category: "legs",
    muscleGroups: ["quads", "glutes"],
    equipment: "machine",
    isBodyweight: false,
    difficulty: "intermediate",
    beginnerCueEn: "Feet shoulder-width on platform, squat deep, press back up through heels.",
    beginnerCueTh: "วางเท้ากว้างระดับไหล่บนแท่น สควอตลึก กดขึ้นผ่านส้นเท้า",
    commonMistakeEn: "Letting lower back peel off the pad at the bottom of the movement.",
    commonMistakeTh: "ปล่อยให้หลังส่วนล่างยกออกจากพนักที่ด้านล่างของการเคลื่อนไหว",
  },
  {
    slug: "split-squat",
    nameEn: "Bulgarian Split Squat",
    nameTh: "บัลกาเรียนสปลิตสควอต",
    category: "legs",
    muscleGroups: ["quads", "glutes", "hamstrings"],
    equipment: "dumbbell",
    isBodyweight: false,
    difficulty: "intermediate",
    beginnerCueEn: "Rear foot on bench, lunge down until front thigh is parallel, drive up through heel.",
    beginnerCueTh: "วางเท้าหลังบนม้านั่ง ลดลงจนต้นขาหน้าขนานพื้น ดันขึ้นผ่านส้นเท้า",
    commonMistakeEn: "Placing the front foot too close, causing knee to travel far past toes.",
    commonMistakeTh: "วางเท้าหน้าใกล้เกินไปทำให้เข่าเลยนิ้วเท้าไปมาก",
  },
  {
    slug: "walking-lunge",
    nameEn: "Walking Lunge",
    nameTh: "วอล์คกิ้งลันจ์",
    category: "legs",
    muscleGroups: ["quads", "glutes", "hamstrings"],
    equipment: "dumbbell",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Step forward, lower back knee toward floor, drive through front heel to step forward.",
    beginnerCueTh: "ก้าวไปข้างหน้า ลดเข่าหลังลงพื้น ดันผ่านส้นเท้าหน้าเพื่อก้าวต่อ",
    commonMistakeEn: "Short strides that cause too much forward lean.",
    commonMistakeTh: "ก้าวสั้นเกินไปทำให้เอนตัวไปข้างหน้ามาก",
  },
  {
    slug: "step-up",
    nameEn: "Step-Up",
    nameTh: "สเต็ปอัพ",
    category: "legs",
    muscleGroups: ["quads", "glutes"],
    equipment: "dumbbell",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Place full foot on box, drive through that heel to step up, bring other foot up.",
    beginnerCueTh: "วางเท้าทั้งหมดบนกล่อง ดันผ่านส้นเท้านั้นเพื่อขึ้นไป นำเท้าอีกข้างขึ้นตาม",
    commonMistakeEn: "Pushing off the back foot instead of working the lead leg.",
    commonMistakeTh: "ผลักจากเท้าหลังแทนที่จะทำงานกับขาหน้า",
  },
  {
    slug: "hip-thrust",
    nameEn: "Hip Thrust",
    nameTh: "ฮิปทรัสต์",
    category: "legs",
    muscleGroups: ["glutes", "hamstrings"],
    equipment: "barbell",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Upper back on bench, bar over hips, drive hips up until body is straight, squeeze glutes at top.",
    beginnerCueTh: "วางหลังส่วนบนบนม้านั่ง บาร์อยู่เหนือสะโพก ดันสะโพกขึ้นจนลำตัวตรง บีบก้นที่ด้านบน",
    commonMistakeEn: "Hyperextending the lower back at the top instead of a neutral spine.",
    commonMistakeTh: "โก่งหลังส่วนล่างมากเกินไปที่ด้านบนแทนที่จะรักษากระดูกสันหลังเป็นกลาง",
  },
  {
    slug: "sumo-deadlift",
    nameEn: "Sumo Deadlift",
    nameTh: "ซูโมเดดลิฟต์",
    category: "legs",
    muscleGroups: ["glutes", "hamstrings", "quads", "back"],
    equipment: "barbell",
    isBodyweight: false,
    difficulty: "intermediate",
    beginnerCueEn: "Wide stance with toes pointed out, grip between feet, keep torso more upright than conventional.",
    beginnerCueTh: "ยืนกว้างโดยให้นิ้วเท้าชี้ออก จับบาร์ระหว่างเท้า รักษาลำตัวให้ตั้งตรงกว่าแบบปกติ",
    commonMistakeEn: "Allowing knees to collapse inward at the start of the pull.",
    commonMistakeTh: "ปล่อยให้เข่าพับเข้าด้านในตอนเริ่มดึง",
  },
  {
    slug: "goblet-squat",
    nameEn: "Goblet Squat",
    nameTh: "ก็อบเล็ตสควอต",
    category: "legs",
    muscleGroups: ["quads", "glutes", "core"],
    equipment: "dumbbell",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Hold dumbbell vertically at chest, squat with upright torso, elbows inside knees.",
    beginnerCueTh: "ถือดัมเบลแนวตั้งที่อก สควอตพร้อมลำตัวตรง ข้อศอกอยู่ด้านในเข่า",
    commonMistakeEn: "Allowing the dumbbell to pull you forward and rounding the upper back.",
    commonMistakeTh: "ปล่อยให้ดัมเบลดึงตัวไปข้างหน้าและโค้งหลังส่วนบน",
  },
  {
    slug: "box-squat",
    nameEn: "Box Squat",
    nameTh: "บ็อกซ์สควอต",
    category: "legs",
    muscleGroups: ["quads", "glutes", "hamstrings"],
    equipment: "barbell",
    isBodyweight: false,
    difficulty: "intermediate",
    beginnerCueEn: "Set box to parallel height, sit back onto box fully, pause, then drive up.",
    beginnerCueTh: "ตั้งกล่องที่ความสูงขนาน นั่งลงบนกล่องเต็มที่ หยุดสักครู่ แล้วดันขึ้น",
    commonMistakeEn: "Bouncing off the box or leaning forward excessively while sitting back.",
    commonMistakeTh: "กระดอนออกจากกล่องหรือเอนตัวไปข้างหน้ามากเกินไปขณะนั่งลง",
  },

  // ─── SHOULDERS (8) ─────────────────────────────────────────────────────────
  {
    slug: "overhead-press",
    nameEn: "Overhead Press",
    nameTh: "โอเวอร์เฮดเพรส",
    category: "shoulders",
    muscleGroups: ["shoulders", "triceps", "upper chest", "core"],
    equipment: "barbell",
    isBodyweight: false,
    difficulty: "intermediate",
    beginnerCueEn: "Grip just outside shoulders, press bar overhead, push head through at top.",
    beginnerCueTh: "จับบาร์ด้านนอกไหล่เล็กน้อย กดบาร์ขึ้นเหนือหัว ดันหัวผ่านออกมาที่ด้านบน",
    commonMistakeEn: "Leaning back excessively, turning it into an incline press.",
    commonMistakeTh: "เอนไปข้างหลังมากเกินไปจนกลายเป็นเบนช์เพรสเอียงขึ้น",
  },
  {
    slug: "dumbbell-shoulder-press",
    nameEn: "Dumbbell Shoulder Press",
    nameTh: "ดัมเบลกดไหล่",
    category: "shoulders",
    muscleGroups: ["shoulders", "triceps"],
    equipment: "dumbbell",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Start with dumbbells at ear height, press overhead until arms are straight.",
    beginnerCueTh: "เริ่มต้นด้วยดัมเบลที่ระดับหู กดขึ้นเหนือหัวจนแขนเหยียดตรง",
    commonMistakeEn: "Arching the lower back to help push the weight up.",
    commonMistakeTh: "โก่งหลังส่วนล่างเพื่อช่วยดันน้ำหนักขึ้น",
  },
  {
    slug: "lateral-raise",
    nameEn: "Lateral Raise",
    nameTh: "ยกแขนด้านข้าง",
    category: "shoulders",
    muscleGroups: ["side delts"],
    equipment: "dumbbell",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Slight bend in elbows, raise dumbbells to shoulder height, lead with elbows.",
    beginnerCueTh: "งอข้อศอกเล็กน้อย ยกดัมเบลขึ้นถึงระดับไหล่ นำด้วยข้อศอก",
    commonMistakeEn: "Shrugging the traps to swing the weight up.",
    commonMistakeTh: "ยักแทรพส์เพื่อเหวี่ยงน้ำหนักขึ้น",
  },
  {
    slug: "front-raise",
    nameEn: "Front Raise",
    nameTh: "ยกแขนด้านหน้า",
    category: "shoulders",
    muscleGroups: ["front delts"],
    equipment: "dumbbell",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Arms hanging, raise dumbbell forward to shoulder height, lower under control.",
    beginnerCueTh: "ห้อยแขนไว้ ยกดัมเบลไปข้างหน้าถึงระดับไหล่ ลดลงอย่างควบคุม",
    commonMistakeEn: "Swinging the torso backward to use momentum.",
    commonMistakeTh: "แกว่งลำตัวไปข้างหลังเพื่อใช้แรงเหวี่ยง",
  },
  {
    slug: "rear-delt-fly",
    nameEn: "Rear Delt Fly",
    nameTh: "ยกแขนหลังไหล่",
    category: "shoulders",
    muscleGroups: ["rear delts", "traps"],
    equipment: "dumbbell",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Hinge to ~45°, raise dumbbells out to sides, squeeze rear delts.",
    beginnerCueTh: "พับตัวประมาณ 45° ยกดัมเบลออกด้านข้าง บีบเดลต์ด้านหลัง",
    commonMistakeEn: "Using too heavy a weight and bending elbows, turning it into a row.",
    commonMistakeTh: "ใช้น้ำหนักหนักเกินและงอข้อศอกจนกลายเป็นโรว์",
  },
  {
    slug: "arnold-press",
    nameEn: "Arnold Press",
    nameTh: "อาร์โนลด์เพรส",
    category: "shoulders",
    muscleGroups: ["shoulders", "triceps"],
    equipment: "dumbbell",
    isBodyweight: false,
    difficulty: "intermediate",
    beginnerCueEn: "Start with palms facing you, rotate outward as you press up.",
    beginnerCueTh: "เริ่มต้นด้วยฝ่ามือหันเข้าหาคุณ หมุนออกขณะกดขึ้น",
    commonMistakeEn: "Rushing the rotation and losing shoulder stability.",
    commonMistakeTh: "หมุนเร็วเกินไปและเสียความมั่นคงของไหล่",
  },
  {
    slug: "upright-row",
    nameEn: "Upright Row",
    nameTh: "อัพไรท์โรว์",
    category: "shoulders",
    muscleGroups: ["traps", "side delts", "biceps"],
    equipment: "barbell",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Grip shoulder-width, pull bar straight up to chin, lead with elbows.",
    beginnerCueTh: "จับบาร์กว้างระดับไหล่ ดึงบาร์ขึ้นตรงไปยังคาง นำด้วยข้อศอก",
    commonMistakeEn: "Using a narrow grip that impinges the shoulder joint.",
    commonMistakeTh: "จับแคบเกินไปทำให้เกิดการกระทบกันที่ข้อไหล่",
  },
  {
    slug: "cable-lateral-raise",
    nameEn: "Cable Lateral Raise",
    nameTh: "เคเบิลยกด้านข้าง",
    category: "shoulders",
    muscleGroups: ["side delts"],
    equipment: "cable",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Cable at foot level, raise arm across body to shoulder height, constant tension throughout.",
    beginnerCueTh: "เคเบิลอยู่ที่ระดับเท้า ยกแขนข้ามลำตัวขึ้นถึงระดับไหล่ แรงตึงคงที่ตลอด",
    commonMistakeEn: "Pulling the cable with wrist flexion instead of shoulder abduction.",
    commonMistakeTh: "ดึงเคเบิลด้วยการงอข้อมือแทนการกางแขนออกที่ไหล่",
  },

  // ─── ARMS (10) ─────────────────────────────────────────────────────────────
  {
    slug: "barbell-curl",
    nameEn: "Barbell Curl",
    nameTh: "บาร์เบลเคิร์ล",
    category: "arms",
    muscleGroups: ["biceps", "forearms"],
    equipment: "barbell",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Keep elbows at sides, curl bar to chin, squeeze biceps, lower slowly.",
    beginnerCueTh: "รักษาข้อศอกไว้ข้างลำตัว ดึงบาร์ขึ้นถึงคาง บีบไบเซ็บส์ ลดลงช้าๆ",
    commonMistakeEn: "Swinging the back to cheat the weight up.",
    commonMistakeTh: "แกว่งหลังเพื่อโกงยกน้ำหนักขึ้น",
  },
  {
    slug: "dumbbell-curl",
    nameEn: "Dumbbell Curl",
    nameTh: "ดัมเบลเคิร์ล",
    category: "arms",
    muscleGroups: ["biceps"],
    equipment: "dumbbell",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Alternate or simultaneous, supinate wrist at top, keep upper arm still.",
    beginnerCueTh: "สลับหรือพร้อมกัน หมุนข้อมือออกด้านบน รักษาต้นแขนให้อยู่นิ่ง",
    commonMistakeEn: "Flaring elbows forward to initiate the curl.",
    commonMistakeTh: "กางข้อศอกไปข้างหน้าเพื่อเริ่มดึง",
  },
  {
    slug: "hammer-curl",
    nameEn: "Hammer Curl",
    nameTh: "แฮมเมอร์เคิร์ล",
    category: "arms",
    muscleGroups: ["biceps", "brachialis", "forearms"],
    equipment: "dumbbell",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Neutral grip (thumbs up), curl with palm facing inward throughout the movement.",
    beginnerCueTh: "จับแนวกลาง (หัวแม่มือชี้ขึ้น) ดึงโดยฝ่ามือหันเข้าตลอดการเคลื่อนไหว",
    commonMistakeEn: "Rotating the wrist to supinate, losing the neutral-grip advantage.",
    commonMistakeTh: "หมุนข้อมือออกจนเสียประโยชน์ของการจับแนวกลาง",
  },
  {
    slug: "preacher-curl",
    nameEn: "Preacher Curl",
    nameTh: "พรีชเชอร์เคิร์ล",
    category: "arms",
    muscleGroups: ["biceps"],
    equipment: "machine",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Rest upper arms on pad, curl bar to chin, lower slowly to full extension.",
    beginnerCueTh: "วางต้นแขนบนแผ่นรอง ดึงบาร์ขึ้นถึงคาง ลดลงช้าๆ จนเหยียดเต็มที่",
    commonMistakeEn: "Locking out too hard at the bottom, stressing the tendon.",
    commonMistakeTh: "ล็อคข้อศอกแรงเกินที่ด้านล่าง ทำให้เส้นเอ็นรับแรงเกิน",
  },
  {
    slug: "tricep-pushdown",
    nameEn: "Tricep Pushdown",
    nameTh: "ไตรเซ็บส์พุชดาวน์",
    category: "arms",
    muscleGroups: ["triceps"],
    equipment: "cable",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Elbows at sides, push bar down to full extension, keep upper arms stationary.",
    beginnerCueTh: "ข้อศอกชิดลำตัว กดบาร์ลงจนเหยียดเต็มที่ รักษาต้นแขนให้อยู่นิ่ง",
    commonMistakeEn: "Letting elbows flare out and using the shoulders to push.",
    commonMistakeTh: "ปล่อยให้ข้อศอกกางออกและใช้ไหล่กด",
  },
  {
    slug: "skull-crusher",
    nameEn: "Skull Crusher",
    nameTh: "สกัลครัชเชอร์",
    category: "arms",
    muscleGroups: ["triceps"],
    equipment: "barbell",
    isBodyweight: false,
    difficulty: "intermediate",
    beginnerCueEn: "Lying with bar above face, lower bar to forehead by bending elbows only.",
    beginnerCueTh: "นอนราบพร้อมบาร์เหนือใบหน้า ลดบาร์มายังหน้าผากโดยงอเฉพาะข้อศอก",
    commonMistakeEn: "Letting upper arms drift back, turning it into a pullover.",
    commonMistakeTh: "ปล่อยให้ต้นแขนเอนไปข้างหลัง กลายเป็นพูลโอเวอร์",
  },
  {
    slug: "overhead-tricep-extension",
    nameEn: "Overhead Tricep Extension",
    nameTh: "โอเวอร์เฮดไตรเซ็บส์เอ็กซ์เทนชั่น",
    category: "arms",
    muscleGroups: ["triceps"],
    equipment: "dumbbell",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Hold dumbbell overhead with both hands, lower behind head by bending elbows.",
    beginnerCueTh: "ถือดัมเบลเหนือหัวด้วยสองมือ ลดลงด้านหลังหัวโดยงอข้อศอก",
    commonMistakeEn: "Flaring elbows out wide instead of keeping them pointing forward.",
    commonMistakeTh: "กางข้อศอกออกกว้างแทนที่จะชี้ไปข้างหน้า",
  },
  {
    slug: "close-grip-bench",
    nameEn: "Close Grip Bench Press",
    nameTh: "เบนช์เพรสจับแคบ",
    category: "arms",
    muscleGroups: ["triceps", "chest"],
    equipment: "barbell",
    isBodyweight: false,
    difficulty: "intermediate",
    beginnerCueEn: "Grip shoulder-width, lower to lower chest, keep elbows tucked.",
    beginnerCueTh: "จับบาร์กว้างระดับไหล่ ลดลงที่อกล่าง รักษาข้อศอกให้ชิด",
    commonMistakeEn: "Gripping too narrow causing wrist pain.",
    commonMistakeTh: "จับแคบเกินไปทำให้เจ็บข้อมือ",
  },
  {
    slug: "tricep-dip",
    nameEn: "Tricep Dip",
    nameTh: "ดิปส์ไตรเซ็บส์",
    category: "arms",
    muscleGroups: ["triceps", "chest"],
    equipment: "bodyweight",
    isBodyweight: true,
    difficulty: "intermediate",
    beginnerCueEn: "Keep torso upright, lower until elbows are 90°, press back up.",
    beginnerCueTh: "รักษาลำตัวให้ตั้งตรง ลดลงจนข้อศอกงอ 90° กดขึ้น",
    commonMistakeEn: "Leaning forward too much, shifting focus to chest.",
    commonMistakeTh: "เอนไปข้างหน้ามากเกินไปทำให้เน้นที่อกแทน",
  },
  {
    slug: "concentration-curl",
    nameEn: "Concentration Curl",
    nameTh: "คอนเซนเตรชั่นเคิร์ล",
    category: "arms",
    muscleGroups: ["biceps"],
    equipment: "dumbbell",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Brace elbow on inner thigh, curl dumbbell, fully supinate at top.",
    beginnerCueTh: "พักข้อศอกที่ต้นขาด้านใน ดึงดัมเบลขึ้น หมุนข้อมือออกเต็มที่ด้านบน",
    commonMistakeEn: "Swinging the arm free instead of bracing on the thigh.",
    commonMistakeTh: "แกว่งแขนอิสระแทนที่จะพักบนต้นขา",
  },

  // ─── CORE (9) ──────────────────────────────────────────────────────────────
  {
    slug: "plank",
    nameEn: "Plank",
    nameTh: "แพลงก์",
    category: "core",
    muscleGroups: ["core", "shoulders", "glutes"],
    equipment: "bodyweight",
    isBodyweight: true,
    difficulty: "beginner",
    beginnerCueEn: "Forearms on floor, hips level, squeeze abs and glutes, breathe steadily.",
    beginnerCueTh: "วางปลายแขนบนพื้น สะโพกระนาบ บีบหน้าท้องและก้น หายใจสม่ำเสมอ",
    commonMistakeEn: "Letting hips sag or piking too high.",
    commonMistakeTh: "ปล่อยสะโพกห้อยลงหรือยกสูงเกินไป",
  },
  {
    slug: "crunch",
    nameEn: "Crunch",
    nameTh: "ครันช์",
    category: "core",
    muscleGroups: ["abs"],
    equipment: "bodyweight",
    isBodyweight: true,
    difficulty: "beginner",
    beginnerCueEn: "Curl shoulder blades off floor, exhale hard at top, lower under control.",
    beginnerCueTh: "ม้วนสะบักขึ้นจากพื้น หายใจออกแรงด้านบน ลดลงอย่างควบคุม",
    commonMistakeEn: "Pulling on the neck instead of curling the abs.",
    commonMistakeTh: "ดึงคอแทนที่จะม้วนหน้าท้อง",
  },
  {
    slug: "leg-raise",
    nameEn: "Hanging Leg Raise",
    nameTh: "แฮงกิ้งเลกเรส",
    category: "core",
    muscleGroups: ["lower abs", "hip flexors"],
    equipment: "bodyweight",
    isBodyweight: true,
    difficulty: "intermediate",
    beginnerCueEn: "Hang from bar, raise legs to parallel (or higher), lower slowly without swinging.",
    beginnerCueTh: "แขวนจากบาร์ ยกขาขึ้นถึงแนวขนาน (หรือสูงกว่า) ลดลงช้าๆ โดยไม่แกว่ง",
    commonMistakeEn: "Swinging the body to use momentum instead of ab strength.",
    commonMistakeTh: "แกว่งลำตัวเพื่อใช้แรงเหวี่ยงแทนความแข็งแรงของหน้าท้อง",
  },
  {
    slug: "russian-twist",
    nameEn: "Russian Twist",
    nameTh: "รัสเซียนทวิสต์",
    category: "core",
    muscleGroups: ["obliques", "abs"],
    equipment: "other",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Sit at 45°, hold plate or dumbbell, rotate side to side touching floor.",
    beginnerCueTh: "นั่งทำมุม 45° ถือแผ่นน้ำหนักหรือดัมเบล หมุนไปด้านข้างสัมผัสพื้น",
    commonMistakeEn: "Moving only arms and not actually rotating the torso.",
    commonMistakeTh: "เคลื่อนแค่แขนและไม่หมุนลำตัวจริงๆ",
  },
  {
    slug: "ab-wheel-rollout",
    nameEn: "Ab Wheel Rollout",
    nameTh: "ล้อหน้าท้อง",
    category: "core",
    muscleGroups: ["abs", "lats", "shoulders"],
    equipment: "other",
    isBodyweight: true,
    difficulty: "advanced",
    beginnerCueEn: "Start on knees, roll wheel forward keeping hips low, pull back using abs and lats.",
    beginnerCueTh: "เริ่มที่เข่า กลิ้งล้อไปข้างหน้าพร้อมรักษาสะโพกต่ำ ดึงกลับโดยใช้หน้าท้องและแลท",
    commonMistakeEn: "Letting the hips drop too far, straining the lower back.",
    commonMistakeTh: "ปล่อยสะโพกลดต่ำเกินไป ทำให้หลังส่วนล่างรับแรงเกิน",
  },
  {
    slug: "cable-crunch",
    nameEn: "Cable Crunch",
    nameTh: "เคเบิลครันช์",
    category: "core",
    muscleGroups: ["abs"],
    equipment: "cable",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Kneel below cable, hold rope at temples, flex spine downward squeezing abs.",
    beginnerCueTh: "คุกเข่าใต้เคเบิล ถือเชือกที่ขมับ งอกระดูกสันหลังลงพร้อมบีบหน้าท้อง",
    commonMistakeEn: "Using hip flexors to pull down instead of crunching the abs.",
    commonMistakeTh: "ใช้กล้ามเนื้อสะโพกดึงลงแทนที่จะม้วนหน้าท้อง",
  },
  {
    slug: "side-plank",
    nameEn: "Side Plank",
    nameTh: "แพลงก์ด้านข้าง",
    category: "core",
    muscleGroups: ["obliques", "core"],
    equipment: "bodyweight",
    isBodyweight: true,
    difficulty: "beginner",
    beginnerCueEn: "Side-lying on forearm, lift hips to form a straight line, hold.",
    beginnerCueTh: "นอนตะแคงพักบนปลายแขน ยกสะโพกขึ้นให้เป็นเส้นตรง ค้างไว้",
    commonMistakeEn: "Allowing the hips to drop, sagging out of alignment.",
    commonMistakeTh: "ปล่อยสะโพกลดลงจนเสียแนวตรง",
  },
  {
    slug: "dead-bug",
    nameEn: "Dead Bug",
    nameTh: "เดดบัก",
    category: "core",
    muscleGroups: ["abs", "core"],
    equipment: "bodyweight",
    isBodyweight: true,
    difficulty: "beginner",
    beginnerCueEn: "Lying on back, arms and knees at 90°, lower opposite arm/leg while pressing low back to floor.",
    beginnerCueTh: "นอนหงาย แขนและเข่างอ 90° ลดแขน/ขาตรงข้ามพร้อมกดหลังส่วนล่างลงพื้น",
    commonMistakeEn: "Allowing the lower back to arch up off the floor.",
    commonMistakeTh: "ปล่อยให้หลังส่วนล่างโก่งขึ้นจากพื้น",
  },
  {
    slug: "hollow-hold",
    nameEn: "Hollow Hold",
    nameTh: "โฮลโลว์โฮลด์",
    category: "core",
    muscleGroups: ["abs", "hip flexors"],
    equipment: "bodyweight",
    isBodyweight: true,
    difficulty: "intermediate",
    beginnerCueEn: "Lying on back, press low back to floor, raise arms and legs creating a banana shape.",
    beginnerCueTh: "นอนหงาย กดหลังส่วนล่างลงพื้น ยกแขนและขาขึ้นสร้างรูปทรงกล้วย",
    commonMistakeEn: "Letting the lower back come off the floor, losing core tension.",
    commonMistakeTh: "ปล่อยให้หลังส่วนล่างยกขึ้นจากพื้น เสียแรงตึงแกนกลาง",
  },

  // ─── CARDIO (8) ────────────────────────────────────────────────────────────
  {
    slug: "treadmill-run",
    nameEn: "Treadmill Run",
    nameTh: "วิ่งสายพาน",
    category: "cardio",
    muscleGroups: ["legs", "cardiovascular"],
    equipment: "machine",
    isBodyweight: true,
    difficulty: "beginner",
    beginnerCueEn: "Land mid-foot, maintain upright posture, keep a comfortable conversational pace.",
    beginnerCueTh: "ลงกลางเท้า รักษาท่าตัวตรง รักษาจังหวะที่สบายพอพูดได้",
    commonMistakeEn: "Over-striding and heel striking, increasing injury risk.",
    commonMistakeTh: "ก้าวยาวเกินและลงด้วยส้นเท้า เพิ่มความเสี่ยงการบาดเจ็บ",
  },
  {
    slug: "cycling",
    nameEn: "Stationary Cycling",
    nameTh: "ปั่นจักรยานอยู่กับที่",
    category: "cardio",
    muscleGroups: ["legs", "cardiovascular"],
    equipment: "machine",
    isBodyweight: true,
    difficulty: "beginner",
    beginnerCueEn: "Set seat so knee has slight bend at bottom, pedal smoothly at a cadence of 80–100 rpm.",
    beginnerCueTh: "ตั้งเบาะให้เข่างอเล็กน้อยที่ด้านล่าง ปั่นสม่ำเสมอที่ความเร็ว 80–100 รอบ/นาที",
    commonMistakeEn: "Setting resistance too high and grinding slow cadence.",
    commonMistakeTh: "ตั้งแรงต้านสูงเกินไปและปั่นช้า",
  },
  {
    slug: "rowing-machine",
    nameEn: "Rowing Machine",
    nameTh: "เครื่องพาย",
    category: "cardio",
    muscleGroups: ["back", "legs", "cardiovascular"],
    equipment: "machine",
    isBodyweight: true,
    difficulty: "beginner",
    beginnerCueEn: "Drive with legs first, lean back slightly, then pull handle to lower chest.",
    beginnerCueTh: "ดันด้วยขาก่อน เอนไปข้างหลังเล็กน้อย แล้วดึงแฮนเดิลมาที่อกล่าง",
    commonMistakeEn: "Pulling with arms first, which is inefficient and strains the back.",
    commonMistakeTh: "ดึงด้วยแขนก่อน ซึ่งไม่มีประสิทธิภาพและทำให้หลังล้า",
  },
  {
    slug: "jump-rope",
    nameEn: "Jump Rope",
    nameTh: "กระโดดเชือก",
    category: "cardio",
    muscleGroups: ["calves", "cardiovascular", "shoulders"],
    equipment: "other",
    isBodyweight: true,
    difficulty: "beginner",
    beginnerCueEn: "Land on balls of feet, keep jumps low and quick, wrists rotate rope not arms.",
    beginnerCueTh: "ลงที่ปลายเท้า กระโดดต่ำและเร็ว ข้อมือหมุนเชือกไม่ใช่แขน",
    commonMistakeEn: "Jumping too high, landing heavy on heels.",
    commonMistakeTh: "กระโดดสูงเกินไป ลงหนักด้วยส้นเท้า",
  },
  {
    slug: "stair-climber",
    nameEn: "Stair Climber",
    nameTh: "เครื่องปีนบันได",
    category: "cardio",
    muscleGroups: ["glutes", "legs", "cardiovascular"],
    equipment: "machine",
    isBodyweight: true,
    difficulty: "beginner",
    beginnerCueEn: "Stand tall, don't lean on handrails, full foot on each step.",
    beginnerCueTh: "ยืนตัวตรง ไม่พิงราวจับ วางเท้าเต็มแต่ละขั้น",
    commonMistakeEn: "Leaning heavily on the handrails, reducing the workout intensity.",
    commonMistakeTh: "พิงราวจับมากเกินไปทำให้ความเข้มข้นการออกกำลังกายลดลง",
  },
  {
    slug: "elliptical",
    nameEn: "Elliptical Trainer",
    nameTh: "เอลลิปติคอล",
    category: "cardio",
    muscleGroups: ["legs", "cardiovascular"],
    equipment: "machine",
    isBodyweight: true,
    difficulty: "beginner",
    beginnerCueEn: "Keep arms and legs in sync, maintain upright posture, push and pull handles equally.",
    beginnerCueTh: "รักษาแขนและขาให้สัมพันธ์กัน รักษาท่าตัวตรง ดัน-ดึงแฮนเดิลเท่าๆ กัน",
    commonMistakeEn: "Leaning on the static handles instead of using the moving arms.",
    commonMistakeTh: "พิงแฮนเดิลที่อยู่นิ่งแทนที่จะใช้แฮนเดิลที่เคลื่อนไหว",
  },
  {
    slug: "sprint-intervals",
    nameEn: "Sprint Intervals",
    nameTh: "วิ่งเร็วสลับพัก",
    category: "cardio",
    muscleGroups: ["legs", "cardiovascular"],
    equipment: "bodyweight",
    isBodyweight: true,
    difficulty: "advanced",
    beginnerCueEn: "Sprint at max effort for 20–30s, walk 60–90s, repeat 6–10 rounds.",
    beginnerCueTh: "วิ่งเร็วสุดกำลังเป็นเวลา 20–30 วินาที เดิน 60–90 วินาที ทำซ้ำ 6–10 รอบ",
    commonMistakeEn: "Not recovering enough between sprints, reducing sprint quality.",
    commonMistakeTh: "พักไม่เพียงพอระหว่างการวิ่ง ทำให้คุณภาพการวิ่งลดลง",
  },
  {
    slug: "battle-ropes",
    nameEn: "Battle Ropes",
    nameTh: "แบตเทิลโรปส์",
    category: "cardio",
    muscleGroups: ["shoulders", "core", "cardiovascular"],
    equipment: "other",
    isBodyweight: true,
    difficulty: "intermediate",
    beginnerCueEn: "Slight squat stance, alternate or simultaneous waves, keep core braced.",
    beginnerCueTh: "ยืนในท่าสควอตเล็กน้อย สลับหรือทำพร้อมกัน รักษาแกนกลางให้แน่น",
    commonMistakeEn: "Using only arms without engaging legs and core.",
    commonMistakeTh: "ใช้แค่แขนโดยไม่ใช้ขาและแกนกลาง",
  },

  // ─── CHEST extras ──────────────────────────────────────────────────────────
  {
    slug: "cable-crossover",
    nameEn: "Cable Crossover",
    nameTh: "เคเบิลครอสโอเวอร์",
    category: "chest",
    muscleGroups: ["chest"],
    equipment: "cable",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Set cables high, step forward and cross handles in front of body, squeeze chest.",
    beginnerCueTh: "ตั้งเคเบิลสูง ก้าวไปข้างหน้าและไขว้แฮนเดิลด้านหน้าลำตัว บีบอก",
    commonMistakeEn: "Using too much weight and losing control of the range of motion.",
    commonMistakeTh: "ใช้น้ำหนักหนักเกินและเสียการควบคุมช่วงการเคลื่อนไหว",
  },
  {
    slug: "incline-dumbbell-fly",
    nameEn: "Incline Dumbbell Fly",
    nameTh: "ดัมเบลฟลายเอียงขึ้น",
    category: "chest",
    muscleGroups: ["upper chest"],
    equipment: "dumbbell",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Set bench to 30°, lower dumbbells in wide arc until slight stretch, squeeze chest back up.",
    beginnerCueTh: "ตั้งม้านั่ง 30° ลดดัมเบลเป็นส่วนโค้งกว้างจนรู้สึกยืดเล็กน้อย บีบอกขึ้น",
    commonMistakeEn: "Setting incline too steep which recruits front delts instead of upper chest.",
    commonMistakeTh: "ตั้งชันเกินไปทำให้เดลต์ด้านหน้าทำงานแทนอกบน",
  },
  {
    slug: "wide-push-up",
    nameEn: "Wide-Grip Push-Up",
    nameTh: "วิดพื้นจับกว้าง",
    category: "chest",
    muscleGroups: ["chest", "triceps"],
    equipment: "bodyweight",
    isBodyweight: true,
    difficulty: "beginner",
    beginnerCueEn: "Hands wider than shoulders, lower chest to floor, elbows flare slightly.",
    beginnerCueTh: "วางมือกว้างกว่าไหล่ ลดอกลงพื้น ข้อศอกกางออกเล็กน้อย",
    commonMistakeEn: "Placing hands too wide, causing shoulder impingement.",
    commonMistakeTh: "วางมือกว้างเกินไปทำให้เกิดการกระทบที่ไหล่",
  },

  // ─── BACK extras ───────────────────────────────────────────────────────────
  {
    slug: "chin-up",
    nameEn: "Chin-Up",
    nameTh: "ชินอัพ",
    category: "back",
    muscleGroups: ["lats", "biceps"],
    equipment: "bodyweight",
    isBodyweight: true,
    difficulty: "intermediate",
    beginnerCueEn: "Underhand grip, pull chest to bar, squeeze lats and biceps at the top.",
    beginnerCueTh: "จับบาร์หงายมือ ดึงอกขึ้นไปหาบาร์ บีบแลทและไบเซ็บส์ที่ด้านบน",
    commonMistakeEn: "Stopping short of full chin-over-bar range of motion.",
    commonMistakeTh: "หยุดก่อนที่คางจะพ้นบาร์",
  },
  {
    slug: "single-arm-lat-pulldown",
    nameEn: "Single-Arm Lat Pulldown",
    nameTh: "แลทพูลดาวน์แขนเดียว",
    category: "back",
    muscleGroups: ["lats", "biceps"],
    equipment: "cable",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Reach fully at top, pull elbow down to hip, squeeze lat fully.",
    beginnerCueTh: "เหยียดเต็มที่ด้านบน ดึงข้อศอกลงมายังสะโพก บีบแลทเต็มที่",
    commonMistakeEn: "Using shoulder rotation rather than true lat engagement.",
    commonMistakeTh: "ใช้การหมุนไหล่แทนที่จะใช้แลทจริงๆ",
  },
  {
    slug: "meadows-row",
    nameEn: "Meadows Row",
    nameTh: "เมโดวส์โรว์",
    category: "back",
    muscleGroups: ["lats", "rear delts", "biceps"],
    equipment: "barbell",
    isBodyweight: false,
    difficulty: "intermediate",
    beginnerCueEn: "Stagger stance perpendicular to bar end, row to hip, full stretch at bottom.",
    beginnerCueTh: "ยืนตั้งฉากกับปลายบาร์ โรว์ขึ้นมาที่สะโพก ยืดเต็มที่ด้านล่าง",
    commonMistakeEn: "Not achieving full range of motion at the bottom stretch.",
    commonMistakeTh: "ไม่ยืดเต็มช่วงที่ด้านล่าง",
  },

  // ─── LEGS extras ───────────────────────────────────────────────────────────
  {
    slug: "seated-leg-curl",
    nameEn: "Seated Leg Curl",
    nameTh: "นั่งดึงเลกเคิร์ล",
    category: "legs",
    muscleGroups: ["hamstrings"],
    equipment: "machine",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Sit upright, press pad down with ankles, curl fully, lower slowly.",
    beginnerCueTh: "นั่งตัวตรง กดแผ่นรองลงด้วยข้อเท้า ดึงเต็มที่ ลดลงช้าๆ",
    commonMistakeEn: "Using momentum to swing the weight instead of controlled curling.",
    commonMistakeTh: "ใช้แรงเหวี่ยงแทนการดึงอย่างควบคุม",
  },
  {
    slug: "single-leg-press",
    nameEn: "Single Leg Press",
    nameTh: "เลกเพรสขาเดียว",
    category: "legs",
    muscleGroups: ["quads", "glutes"],
    equipment: "machine",
    isBodyweight: false,
    difficulty: "intermediate",
    beginnerCueEn: "One foot centered on platform, press to near-full extension, lower controlled.",
    beginnerCueTh: "วางเท้าข้างเดียวตรงกลางแท่น กดจนเกือบเหยียดสุด ลดลงอย่างควบคุม",
    commonMistakeEn: "Allowing the working knee to cave inward under load.",
    commonMistakeTh: "ปล่อยให้เข่าที่ทำงานพับเข้าด้านในเมื่อน้ำหนักหนัก",
  },
  {
    slug: "standing-hamstring-curl",
    nameEn: "Standing Hamstring Curl",
    nameTh: "ยืนดึงแฮมสตริง",
    category: "legs",
    muscleGroups: ["hamstrings"],
    equipment: "machine",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Stand on one leg, curl heel to glute, hold briefly, lower slowly.",
    beginnerCueTh: "ยืนขาเดียว ดึงส้นเท้าขึ้นไปยังก้น ค้างสักครู่ ลดลงช้าๆ",
    commonMistakeEn: "Tilting hips and using lower back to assist the curl.",
    commonMistakeTh: "เอียงสะโพกและใช้หลังส่วนล่างช่วยดึง",
  },
  {
    slug: "adductor-machine",
    nameEn: "Hip Adductor Machine",
    nameTh: "เครื่องหนีบขา",
    category: "legs",
    muscleGroups: ["adductors", "inner thighs"],
    equipment: "machine",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Sit with pads against inner thighs, squeeze legs together, open under control.",
    beginnerCueTh: "นั่งโดยให้แผ่นรองสัมผัสต้นขาด้านใน หนีบขาเข้าหากัน แยกออกอย่างควบคุม",
    commonMistakeEn: "Opening the range too far, overstretching the adductors.",
    commonMistakeTh: "เปิดช่วงการเคลื่อนไหวมากเกินทำให้กล้ามเนื้อด้านในต้นขายืดเกิน",
  },
  {
    slug: "reverse-lunge",
    nameEn: "Reverse Lunge",
    nameTh: "ลันจ์ถอยหลัง",
    category: "legs",
    muscleGroups: ["quads", "glutes", "hamstrings"],
    equipment: "dumbbell",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Step back and lower rear knee toward floor, front thigh parallel, drive through front heel.",
    beginnerCueTh: "ก้าวไปข้างหลังและลดเข่าหลังลงพื้น ต้นขาหน้าขนาน ดันผ่านส้นเท้าหน้า",
    commonMistakeEn: "Letting the front knee cave inward as you push back up.",
    commonMistakeTh: "ปล่อยให้เข่าหน้าพับเข้าด้านในขณะดันขึ้น",
  },

  // ─── SHOULDERS extras ──────────────────────────────────────────────────────
  {
    slug: "band-pull-apart",
    nameEn: "Band Pull Apart",
    nameTh: "ดึงยางยืดออก",
    category: "shoulders",
    muscleGroups: ["rear delts", "traps", "external rotators"],
    equipment: "band",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Hold band at chest height, pull apart horizontally, squeeze shoulder blades.",
    beginnerCueTh: "ถือยางระดับอก ดึงออกแนวนอน บีบสะบักเข้าหากัน",
    commonMistakeEn: "Shrugging traps up as you pull, losing the shoulder-blade retraction.",
    commonMistakeTh: "ยักแทรพส์ขึ้นขณะดึง เสียการหดสะบัก",
  },
  {
    slug: "z-press",
    nameEn: "Z-Press",
    nameTh: "ซี-เพรส",
    category: "shoulders",
    muscleGroups: ["shoulders", "triceps", "core"],
    equipment: "barbell",
    isBodyweight: false,
    difficulty: "advanced",
    beginnerCueEn: "Sit on floor legs straight, press bar overhead, maintain upright torso.",
    beginnerCueTh: "นั่งบนพื้นเหยียดขา กดบาร์ขึ้นเหนือหัว รักษาลำตัวให้ตั้งตรง",
    commonMistakeEn: "Leaning back to compensate for poor thoracic mobility.",
    commonMistakeTh: "เอนหลังเพื่อชดเชยความยืดหยุ่นของกระดูกสันหลังส่วนอกที่ไม่ดี",
  },

  // ─── ARMS extras ───────────────────────────────────────────────────────────
  {
    slug: "reverse-curl",
    nameEn: "Reverse Curl",
    nameTh: "รีเวิร์สเคิร์ล",
    category: "arms",
    muscleGroups: ["brachialis", "forearms"],
    equipment: "barbell",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Overhand grip, curl bar to chin, keep elbows at sides.",
    beginnerCueTh: "จับบาร์คว่ำมือ ดึงบาร์ขึ้นถึงคาง รักษาข้อศอกไว้ข้างลำตัว",
    commonMistakeEn: "Letting wrists flex backward, reducing brachialis engagement.",
    commonMistakeTh: "ปล่อยให้ข้อมืองอไปข้างหลังทำให้กล้ามเนื้อบราเคียลิสทำงานน้อยลง",
  },
  {
    slug: "cable-curl",
    nameEn: "Cable Curl",
    nameTh: "เคเบิลเคิร์ล",
    category: "arms",
    muscleGroups: ["biceps"],
    equipment: "cable",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Stand facing cable, curl bar to chin, constant tension throughout.",
    beginnerCueTh: "ยืนหันหน้าเข้าเคเบิล ดึงบาร์ขึ้นถึงคาง แรงตึงคงที่ตลอด",
    commonMistakeEn: "Stepping too close to the machine, reducing the cable angle advantage.",
    commonMistakeTh: "ยืนชิดเครื่องเกินไปทำให้เสียข้อดีของมุมเคเบิล",
  },
  {
    slug: "wrist-curl",
    nameEn: "Wrist Curl",
    nameTh: "เวิสท์เคิร์ล",
    category: "arms",
    muscleGroups: ["forearms"],
    equipment: "barbell",
    isBodyweight: false,
    difficulty: "beginner",
    beginnerCueEn: "Forearms on bench, curl wrists upward, hold briefly, lower fully.",
    beginnerCueTh: "วางปลายแขนบนม้านั่ง ดึงข้อมือขึ้น ค้างสักครู่ ลดลงเต็มที่",
    commonMistakeEn: "Using too much weight and recruiting the elbow instead of wrist.",
    commonMistakeTh: "ใช้น้ำหนักหนักเกินและใช้ข้อศอกแทนข้อมือ",
  },

  // ─── CORE extras ───────────────────────────────────────────────────────────
  {
    slug: "v-up",
    nameEn: "V-Up",
    nameTh: "วี-อัพ",
    category: "core",
    muscleGroups: ["abs", "hip flexors"],
    equipment: "bodyweight",
    isBodyweight: true,
    difficulty: "intermediate",
    beginnerCueEn: "Simultaneously raise straight legs and upper body, reach hands to feet.",
    beginnerCueTh: "ยกขาตรงและลำตัวส่วนบนพร้อมกัน เอื้อมมือไปถึงเท้า",
    commonMistakeEn: "Bending the knees to make it easier, reducing core demand.",
    commonMistakeTh: "งอเข่าเพื่อให้ง่ายขึ้น ทำให้การทำงานของแกนกลางลดลง",
  },
  {
    slug: "bicycle-crunch",
    nameEn: "Bicycle Crunch",
    nameTh: "ครันช์จักรยาน",
    category: "core",
    muscleGroups: ["obliques", "abs"],
    equipment: "bodyweight",
    isBodyweight: true,
    difficulty: "beginner",
    beginnerCueEn: "Alternate opposite elbow to knee, keep lower back pressed to floor.",
    beginnerCueTh: "สลับข้อศอกตรงข้ามกับเข่า กดหลังส่วนล่างลงพื้น",
    commonMistakeEn: "Pulling on the neck and using momentum rather than twisting the torso.",
    commonMistakeTh: "ดึงคอและใช้แรงเหวี่ยงแทนการหมุนลำตัว",
  },
  {
    slug: "windshield-wiper",
    nameEn: "Windshield Wiper",
    nameTh: "ท่าปัดน้ำฝน",
    category: "core",
    muscleGroups: ["obliques", "abs", "hip flexors"],
    equipment: "bodyweight",
    isBodyweight: true,
    difficulty: "advanced",
    beginnerCueEn: "Lying on back, legs at 90° in air, lower legs side to side without touching floor.",
    beginnerCueTh: "นอนหงาย ขางอ 90° ลอยอยู่ในอากาศ ลดขาไปด้านข้างโดยไม่สัมผัสพื้น",
    commonMistakeEn: "Letting legs drop too fast using gravity, not oblique control.",
    commonMistakeTh: "ปล่อยให้ขาตกเร็วโดยใช้แรงโน้มถ่วงแทนการควบคุมด้วยกล้ามเนื้อข้าง",
  },

  // ─── CARDIO extras ─────────────────────────────────────────────────────────
  {
    slug: "box-jump",
    nameEn: "Box Jump",
    nameTh: "กระโดดกล่อง",
    category: "cardio",
    muscleGroups: ["legs", "glutes", "cardiovascular"],
    equipment: "other",
    isBodyweight: true,
    difficulty: "intermediate",
    beginnerCueEn: "Load hips back, explode up onto box, land softly with bent knees, step down.",
    beginnerCueTh: "โหลดสะโพกไปข้างหลัง ระเบิดขึ้นไปบนกล่อง ลงเบาๆ ด้วยเข่างอ ก้าวลง",
    commonMistakeEn: "Jumping down from the box instead of stepping, increasing impact on joints.",
    commonMistakeTh: "กระโดดลงจากกล่องแทนการก้าวลง ทำให้ข้อต่อรับแรงกระแทกมาก",
  },
  {
    slug: "mountain-climber",
    nameEn: "Mountain Climber",
    nameTh: "ปีนเขา",
    category: "cardio",
    muscleGroups: ["core", "legs", "cardiovascular"],
    equipment: "bodyweight",
    isBodyweight: true,
    difficulty: "beginner",
    beginnerCueEn: "Start in push-up position, drive knees to chest alternately at speed.",
    beginnerCueTh: "เริ่มในท่าวิดพื้น ดึงเข่าสลับไปที่อกด้วยความเร็ว",
    commonMistakeEn: "Raising the hips too high, breaking plank position.",
    commonMistakeTh: "ยกสะโพกสูงเกินไป เสียท่าแพลงก์",
  },
  {
    slug: "high-knees",
    nameEn: "High Knees",
    nameTh: "ยกเข่าสูง",
    category: "cardio",
    muscleGroups: ["legs", "cardiovascular", "core"],
    equipment: "bodyweight",
    isBodyweight: true,
    difficulty: "beginner",
    beginnerCueEn: "Run in place, drive knees above hip level, pump arms in sync.",
    beginnerCueTh: "วิ่งอยู่กับที่ ยกเข่าเหนือระดับสะโพก แกว่งแขนสัมพันธ์กัน",
    commonMistakeEn: "Leaning back and not driving knees high enough.",
    commonMistakeTh: "เอนไปข้างหลังและไม่ยกเข่าสูงพอ",
  },

  // ─── FULL BODY extras ──────────────────────────────────────────────────────
  {
    slug: "kettlebell-swing",
    nameEn: "Kettlebell Swing",
    nameTh: "สวิงเคทเทิลเบล",
    category: "full_body",
    muscleGroups: ["glutes", "hamstrings", "back", "cardiovascular"],
    equipment: "kettlebell",
    isBodyweight: false,
    difficulty: "intermediate",
    beginnerCueEn: "Hip hinge back, hike bell between legs, drive hips forward explosively to shoulder height.",
    beginnerCueTh: "พับสะโพกไปข้างหลัง แกว่งเคทเทิลเบลระหว่างขา ดันสะโพกไปข้างหน้าอย่างระเบิดขึ้นถึงระดับไหล่",
    commonMistakeEn: "Squatting the movement instead of hinging at the hip.",
    commonMistakeTh: "ทำสควอตแทนการพับสะโพก",
  },
  {
    slug: "man-maker",
    nameEn: "Man Maker",
    nameTh: "แมนเมคเกอร์",
    category: "full_body",
    muscleGroups: ["full body", "shoulders", "back", "legs", "core"],
    equipment: "dumbbell",
    isBodyweight: false,
    difficulty: "advanced",
    beginnerCueEn: "Push-up, renegade row each arm, jump feet to hands, stand and press.",
    beginnerCueTh: "วิดพื้น ดึงดัมเบลทีละข้าง กระโดดเท้าเข้าหามือ ยืนและกดขึ้น",
    commonMistakeEn: "Losing core tension during the renegade row portion.",
    commonMistakeTh: "เสียแรงตึงแกนกลางระหว่างส่วนเรเนเกดโรว์",
  },

  // ─── FULL BODY (4) ─────────────────────────────────────────────────────────
  {
    slug: "burpee",
    nameEn: "Burpee",
    nameTh: "เบอร์พี",
    category: "full_body",
    muscleGroups: ["full body", "cardiovascular"],
    equipment: "bodyweight",
    isBodyweight: true,
    difficulty: "intermediate",
    beginnerCueEn: "Squat down, jump feet back to plank, push-up, jump feet forward, jump up with hands overhead.",
    beginnerCueTh: "นั่งสควอต กระโดดเท้าไปข้างหลังในท่าแพลงก์ ดันพื้น กระโดดเท้ามาข้างหน้า กระโดดขึ้นพร้อมยกมือเหนือหัว",
    commonMistakeEn: "Sagging the hips in the plank portion or skipping the push-up.",
    commonMistakeTh: "ปล่อยสะโพกห้อยในท่าแพลงก์หรือข้ามการวิดพื้น",
  },
  {
    slug: "clean-and-press",
    nameEn: "Clean and Press",
    nameTh: "คลีนแอนด์เพรส",
    category: "full_body",
    muscleGroups: ["full body", "shoulders", "legs", "back"],
    equipment: "barbell",
    isBodyweight: false,
    difficulty: "advanced",
    beginnerCueEn: "Deadlift bar, explosively pull to front rack, then press overhead.",
    beginnerCueTh: "ยกบาร์แบบเดดลิฟต์ ดึงขึ้นอย่างระเบิดไปยังตำแหน่งหน้า แล้วกดขึ้นเหนือหัว",
    commonMistakeEn: "Muscling the clean up with arms instead of using leg drive.",
    commonMistakeTh: "ดึงขึ้นด้วยแขนแทนที่จะใช้แรงขา",
  },
  {
    slug: "turkish-get-up",
    nameEn: "Turkish Get-Up",
    nameTh: "เติร์กิชเก็ตอัพ",
    category: "full_body",
    muscleGroups: ["full body", "shoulders", "core"],
    equipment: "kettlebell",
    isBodyweight: false,
    difficulty: "advanced",
    beginnerCueEn: "Arm with weight points straight up throughout, move through each position deliberately.",
    beginnerCueTh: "แขนที่ถือน้ำหนักชี้ตรงขึ้นตลอด เคลื่อนผ่านแต่ละท่าอย่างตั้งใจ",
    commonMistakeEn: "Rushing through positions and losing the locked-out arm overhead.",
    commonMistakeTh: "รีบผ่านท่าต่างๆ และเสียตำแหน่งล็อคแขนเหนือหัว",
  },
  {
    slug: "thruster",
    nameEn: "Thruster",
    nameTh: "ทรัสเตอร์",
    category: "full_body",
    muscleGroups: ["quads", "shoulders", "core", "glutes"],
    equipment: "barbell",
    isBodyweight: false,
    difficulty: "advanced",
    beginnerCueEn: "Front squat into overhead press in one fluid motion, use leg drive to power the press.",
    beginnerCueTh: "ฟรอนต์สควอตต่อเนื่องเป็นโอเวอร์เฮดเพรสในท่าเดียว ใช้แรงขาในการกด",
    commonMistakeEn: "Pausing between the squat and press, losing the momentum.",
    commonMistakeTh: "หยุดระหว่างสควอตและกด ทำให้เสียแรงเหวี่ยง",
  },
];
